apiVersion: v1
kind: Namespace
metadata:
  name: rancher

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-server
  namespace: rancher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-server
  template:
    metadata:
      labels:
        app: rancher-server
    spec:
      containers:
      - name: rancher-server
        image: rancher/rancher:v2.3.4-rc8
        ports:
          - containerPort: 80
          - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: rancher-server
  namespace: rancher 
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rancher-server
