apiVersion: v1
kind: Service
metadata:
  name: svc-external
  namespace: gitlab
  labels:
    service: external
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8929
      targetPort: 8929
---
apiVersion: v1
kind: Endpoints
metadata:
  name: svc-external
  namespace: gitlab
  labels:
    service: external-ep
subsets:
  - addresses:
      - ip: 192.168.1.11
    ports:
      - port: 8929
        name: http