# https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes

install-cert-manager:
	helm repo add jetstack https://charts.jetstack.io
	helm install cert-manager jetstack/cert-manager --namespace cert-manager